// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duuiigirpmrfnvbwiema.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1dWlpZ2lycG1yZm52YndpZW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMTQ2MjksImV4cCI6MjA5MDU5MDYyOX0.018qD6JAt7F3gSgGfA65wo5n9ZUnJ8yocYVLgv6fi0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});